### ISSUE TITLE
Games crashing

### ISSUE THREAD

**Issue by 32bitx64bit** [TheComputerGuy96/wine-tkg-git#2]
Some games crash idk why they do
Here are some of the games that crash (Perhaps we could get a patch for them)
Aeronautica 
https://www.roblox.com/games/6647962258/New-Continent-Aeronautica
AR2 (Doesn't load correctly most of the time and if it does it will lag a lot then proceed to crash)
https://www.roblox.com/games/863266079/Apocalypse-Rising-2-Alpha (paid access so i wouldnt expect a patch for it)

**Comment by TheComputerGuy96** [comment]
@32bitx64bit This is due to Wine's RAM limitations in 32-bit mode (which are hit by memory leaks or something else?)

Roblox now has a 64-bit client (which will workaround this), but it doesn't work on Wine right now (Hyperion issue?)

**Comment by 32bitx64bit** [comment]
Forgot about this issue. It was solved sense roblox's 64 bit update. Also solved under Sober. (the new roblox client on linux,)
